In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mlp
import matplotlib.pyplot as plt
import pickle
import sklearn
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import tree

# Data Import

In [3]:
df_X, df_y = datasets.load_iris(return_X_y=True, as_frame = True)

# Data Prep

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df_X, df_y, test_size=0.30)

# Model Training

In [5]:
model = tree.DecisionTreeClassifier()

In [6]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

# Model Evaluation

In [7]:
pred = model.predict(X_test)

In [8]:
print(confusion_matrix(y_test,pred))

[[12  0  0]
 [ 0 12  2]
 [ 0  0 19]]


In [9]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.86      0.92        14
           2       0.90      1.00      0.95        19

    accuracy                           0.96        45
   macro avg       0.97      0.95      0.96        45
weighted avg       0.96      0.96      0.95        45



# Model Export for Deployment

In [10]:
pickle.dump(model, open('model.pkl', 'wb'))